<?php
	$categories = $this->getCategoryCollection();
	$categoryHelper = $this->getCategoryHelper();
	$canShowImg = $this->canShowImage();
	$title = __($block->getTitle());
	$currentCat  = $block->getCurrentCategory();
?>
<div class="category_list_widget">
	<?php if ($title):?>
	<div class="block-title">
		<strong><?php echo $block->escapeHtml($title) ?></strong>
	</div>
	<?php endif ?>

	<div class="block-content catalog-category">
		<?php foreach($categories as $category):?>
		<?php if ($category->getIncludeInMenu()): ?>
		<?php
			$imageWidth = $this->getImageWidth();
			$imageHeight = $this->getImageHeight();
			$additionalImage = $block->escapeUrl($category->getData('additional_image'));
			$placeHolder = $this->getViewFileUrl('Buro210_CategoryList::images/placeholder.png');
			$categoryID = $block->escapeHtml($category->getId());
			$categoryTitle = $block->escapeHtml($category->getName());
			$curerntCatID = (!empty($currentCat) ? $curerntCatID = $block->escapeHtml($currentCat->getId()) : $curerntCatID = 0);
		?>
		<?php if ($categoryID != $curerntCatID) : ?>

		<div class="category id-<?php echo $categoryID; ?>">
			<a href="<?php echo $block->escapeUrl($category->getUrl()) ?>">

				<?php if($canShowImg && $category->getData('additional_image')): ?>
					<img src="<?php echo $block->resize($additionalImage,$imageWidth,$imageHeight); ?>" alt="" width="<?php echo $imageWidth; ?>" height="<?php echo $imageHeight; ?>"/>
				<?php else: ?>
					<img src="<?php echo $placeHolder; ?>" alt=""/>
				<?php endif; ?>

				<span class="cat-title"><?php echo $categoryTitle; ?></span>
			</a>
		</div>
		<?php /*else: ?>
		<div class="category current id-<?php echo $categoryID; ?>">
			<a href="<?php echo $block->escapeUrl($currentCat->getParentCategory()->getUrl()) ?>">
				<div class="current_wrapper">
					<div class="current_text">
						<?php echo __('Current category'); ?>
					</div>
					<span class="all_link"><?php echo __('Back to homepage'); ?></span>
				</div>
			</a>
		</div>
		<?php endif; */?>
		<?php endif; ?>
		<?php endif; ?>
		<?php endforeach; ?>
	</div>
</div>
