<?php
	$categories = $this->getCategoryCollection();
	$categoryHelper = $this->getCategoryHelper();
	$canShowImg = $this->canShowImage();
	$title = $block->getTitle() ? __($block->getTitle()) : 'Categories';
?>
<div class="category_list_widget">
	<?php if ($title):?>
	<div class="block-title">
		<strong><?php echo $block->escapeHtml($title) ?></strong>
	</div>
	<?php endif ?>

	<div class="block-content catalog-category">
		<?php foreach($categories as $category):?>
		<?php if ($category->getIncludeInMenu()): ?>
		<div class="category">
			<a href="<?php echo $block->escapeUrl($category->getUrl()) ?>">
				<?php if($canShowImg && $category->getImageUrl()):?>
				<img src="<?php echo $block->escapeUrl($category->getData('additional_image')) ?>" alt="" width="<?=$this->getImageWidth();?>" height="<?=$this->getImageHeight()?>"/>
				<?php elseif($canShowImg && !$category->getData('additional_image')):?>
				<img src="<?php echo $this->getViewFileUrl('Buro210_Categorylist::images/placeholder.png'); ?>" alt="" width="<?=$this->getImageWidth();?>" height="<?=$this->getImageHeight()?>"/>
				<?php else: ?>
				<?php endif;?>
				<span class="cat-title"><?php echo $block->escapeHtml($category->getName()) ?></span>
			</a>
		</div>
		<?php endif; ?>
		<?php endforeach; ?>
	</div>
</div>
